# Base image
FROM node:18-alpine

# Install Nodemon globally
RUN npm install -g nodemon

# Set working directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Copy app source
COPY . .

# Expose port
EXPOSE 3000

# Start the app with Nodemon for development
CMD ["nodemon", "server/index.js"]
